r"""Flatten TreadLab into ONE self-contained .html file.

    python-embed\python.exe tools\make_single_file.py [outfile]

The result needs nothing but a browser: no Python, no web server, no
network, no GitHub. Double-click it on any operating system and TreadLab
runs from the file itself. It is the long-term escape hatch -- if the
bundled Python stops running on some future Windows, or the GitHub Pages
copy disappears, this file still works.

Two things it deliberately gives up, both consequences of file:// not
being a "secure context" in browsers:

  * live Bluetooth HR straps (navigator.bluetooth is undefined)
  * reliable localStorage, so the saved plan may not survive a reload

The normal TreadLab.bat copy keeps both, which is why this is the
fallback and not the main way to run it.

NEVER edit the generated file by hand -- it is rebuilt from source by
make_web_build.py on every publish, and hand edits would be silently
overwritten.

How the flattening works: the app is 8 ES modules. They cannot simply be
concatenated -- merge.js and app.js BOTH define `lowerBound`, index.js
and app.js both define `pad2`, so one would clobber the other. Instead
each module keeps its own scope inside a function, and a tiny registry
wires the imports together, preserving exact ES-module semantics.
"""

import os
import posixpath
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "treadlab", "static")
ENTRY = "app.js"
DEFAULT_NAME = "TreadLab-any-computer.html"

# import { a, b } from "./x.js";   (also spanning several lines)
IMPORT_RE = re.compile(
    r'^import\s*\{([^}]*)\}\s*from\s*["\']([^"\']+)["\']\s*;?[ \t]*$',
    re.M | re.S)
# export const X / export function f / export class C
EXPORT_DECL_RE = re.compile(
    r'^export\s+(?=(?:async\s+)?(?:const|let|var|function|class)\s+'
    r'([A-Za-z_$][\w$]*))', re.M)
# export { a, b };
EXPORT_LIST_RE = re.compile(r'^export\s*\{([^}]*)\}\s*;?[ \t]*$', re.M)


def read(rel):
    with open(os.path.join(SRC, rel.replace("/", os.sep)), encoding="utf-8") as fh:
        return fh.read()


def split_names(blob):
    """"a, b as c," -> [(imported, local), ...]"""
    out = []
    for part in blob.split(","):
        part = part.strip()
        if not part:
            continue
        if " as " in part:
            src, dst = (p.strip() for p in part.split(" as ", 1))
        else:
            src = dst = part
        out.append((src, dst))
    return out


def load_module(rel, modules, stack):
    """Parse one module, recursing into its imports. Fills `modules`."""
    if rel in modules:
        return
    if rel in stack:
        raise SystemExit("  import cycle: %s" % " -> ".join(stack + [rel]))

    src = read(rel)
    here = posixpath.dirname(rel)
    deps = []

    def take_import(m):
        target = posixpath.normpath(posixpath.join(here, m.group(2)))
        deps.append(target)
        pairs = split_names(m.group(1))
        binding = ", ".join(s if s == d else "%s: %s" % (s, d) for s, d in pairs)
        return '  const { %s } = __req("%s");' % (binding, target)

    src = IMPORT_RE.sub(take_import, src)

    exported = []
    for m in EXPORT_DECL_RE.finditer(src):
        exported.append(m.group(1))
    src = EXPORT_DECL_RE.sub("", src)

    for m in EXPORT_LIST_RE.finditer(src):
        exported.extend(d for _, d in split_names(m.group(1)))
    src = EXPORT_LIST_RE.sub("", src)

    modules[rel] = {"src": src, "exports": exported}
    stack.append(rel)
    for dep in deps:
        load_module(dep, modules, stack)
    stack.pop()


def bundle():
    modules = {}
    load_module(ENTRY, modules, [])

    parts = ["""(function () {
"use strict";
/* TreadLab single-file build -- GENERATED by tools/make_single_file.py.
   Do not edit: rebuilt from treadlab/static/ on every publish.
   Each module below keeps its own scope, exactly as ES modules do. */
var __reg = {}, __done = {};
function __def(id, fn) { __reg[id] = fn; }
function __req(id) {
  if (!Object.prototype.hasOwnProperty.call(__done, id)) {
    if (!__reg[id]) { throw new Error("TreadLab: missing module " + id); }
    __done[id] = __reg[id]();
  }
  return __done[id];
}"""]

    for rel in sorted(modules):
        mod = modules[rel]
        returns = ", ".join(sorted(mod["exports"]))
        parts.append('__def("%s", function () {\n%s\nreturn { %s };\n});'
                     % (rel, mod["src"].strip("\n"), returns))

    parts.append('__req("%s");\n})();' % ENTRY)
    return modules, "\n\n".join(parts)


def build(out, quiet=False):
    """Write the flattened single-file app to `out`. Returns its size."""
    modules, js = bundle()
    html = read("index.html")
    css = read("style.css")

    # Inline the stylesheet.
    html, n = re.subn(r'[ \t]*<link rel="stylesheet" href="style\.css">',
                      "<style>\n%s\n</style>" % css.strip(), html)
    if n != 1:
        raise SystemExit("  could not find the stylesheet link in index.html")

    # Drop the two links that only make sense when served over http(s):
    # the PWA manifest and the apple-touch-icon (a separate .png file).
    # The favicon stays -- it is already an inline data: URI.
    html, n_drop = re.subn(
        r'[ \t]*<link rel="(?:manifest|apple-touch-icon)"[^>]*>\n', "", html)

    # Inline the script. A classic script, not type="module": inline
    # modules would work too, but a plain IIFE sidesteps every remaining
    # file:// module question, and "use strict" above keeps the same
    # semantics. It stays at the end of <body>, so the DOMContentLoaded
    # listener app.js registers still fires.
    html, n = re.subn(r'[ \t]*<script type="module" src="app\.js"></script>',
                      "<script>\n%s\n</script>" % js, html)
    if n != 1:
        raise SystemExit("  could not find the app.js script tag in index.html")

    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(html)

    size = os.path.getsize(out)
    if not quiet:
        print("  %d modules flattened, %d http-only links dropped"
              % (len(modules), n_drop))
        for rel in sorted(modules):
            print("    %-22s %2d exports" % (rel, len(modules[rel]["exports"])))
    print("  -> %s  (%.0f KB)" % (out, size / 1024.0))
    return size


def main():
    build(sys.argv[1] if len(sys.argv) > 1
          else os.path.join(ROOT, DEFAULT_NAME))


if __name__ == "__main__":
    main()
